[package]

name = "1"
version = "0.0.1"
authors = ["Jakub Pastuszek <jpastuszek@gmail.com>"]

[dependencies]
clap = "*"
log = "0.2"
env_logger = "*"
nanomsg = "0.3.1"
chrono = "0.2"

[dependencies.msgpack]
git = "https://github.com/mneumann/rust-msgpack.git"
