[package]
name = "rdms-test"
version = "0.0.1"
authors = ["Jakub Pastuszek <jpastuszek@gmail.com>"]

[dependencies]
clap = "*"
log = "*"
env_logger = "*"
nanomsg = "*"
chrono = "*"
capnp = "*"
capnpc = "*"
stainless = "*"

