[package]
name = "rdms-test"
version = "0.0.1"
authors = ["Jakub Pastuszek <jpastuszek@gmail.com>"]

[dependencies]
clap = "*"
log = "0.2"
env_logger = "*"
nanomsg = "0.3.1"
chrono = "0.2"
capnp = "*"
capnpc = "*"
